"""add configuracao table

Revision ID: e8b04cc4e1d4
Revises: 4534a30bffed
Create Date: 2026-08-26 20:52:12.034733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8b04cc4e1d4'
down_revision: Union[str, Sequence[str], None] = '4534a30bffed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracao',
    sa.Column('chave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Boolean(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('chave')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracao')
    # ### end Alembic commands ###
