"""baseline: current schema

Revision ID: 1c4281515f25
Revises:
Create Date: 2026-08-26 12:44:09.234576

NOTE: an existing dev/prod auditoria.db that already has log_auditoria
(created via the old AuditBase.metadata.create_all) must NOT run
`alembic upgrade head` against this revision — it would fail trying to
create a table that already exists. Instead, adopt the baseline without
touching the schema:

    alembic -c alembic_audit.ini stamp 1c4281515f25

A fresh audit database (no tables yet) should just run
`alembic -c alembic_audit.ini upgrade head` as usual.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c4281515f25'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=False),
    sa.Column('acao', sa.String(length=20), nullable=False),
    sa.Column('entidade', sa.String(length=20), nullable=False),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.Column('ip_origem', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_auditoria')
    # ### end Alembic commands ###
